name: Delete old workflow runs
on:
  schedule: [cron: '30 10 * * *']
  workflow_dispatch: {}
    
jobs:
  Cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup workflow runs
        uses: iamludal/action-purge-workflow-runs@v2
        with:
          days-old: 14
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}