name: Help Docs

on:
  workflow_run:
    workflows: [Unit Test]
    types: [completed]
  workflow_dispatch: {}

jobs:
  Docs:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch'}}
    runs-on: windows-latest
    steps:
      - name: Checkout Self
        uses: actions/checkout@v3
      
      - name: Setup Unity
        id: setup-unity
        uses: kuler90/setup-unity@v1
        with:
          project-path: chatlyst-dev/
       
      - name: Execute Unity
        uses: Morsiusiurandum/unity-runner@beta
        with:
          unity-path: ${{steps.setup-unity.outputs.unity-path}}
          unity-username: ${{ secrets.UNITY_EMAIL_WIN }}
          unity-password: ${{ secrets.UNITY_PASSWORD_WIN }}
          unity-ulf: ${{ secrets.UNITY_LICENSE_WIN }}
          project-path: "chatlyst-dev"
          execute-method: SyncVS_Workaround.SyncSolution

      - name: Dotnet Setup
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x

      - name: Setup Docfx
        run: dotnet tool update -g docfx

      - name: Build Site
        run: docfx docs/docfx.json

      - name: Deploy site
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: docs/_site
