name: Help Docs -test

on:
  push:
     
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  Docs:
    runs-on: windows-latest
    steps:
      - name: Checkout Self
        uses: actions/checkout@v3
      
      - name: Setup Unity
        id: setup-unity
        uses: kuler90/setup-unity@v1
        with:
          project-path: chatlyst-dev/
       
      - name: Activate Unity
        uses: Morsiusiurandum/unity-runner@main
        with:
          unity-path: ${{steps.setup-unity.outputs.unity-path}}
          unity-username: ${{ secrets.UNITY_EMAIL }}
          unity-password: ${{ secrets.UNITY_PASSWORD }}
          unity-alf: ${{ secrets.UNITY_SERIAL }}
          project-path: "chatlyst-dev"
          execute-method: SyncVS_Workaround.SyncSolution

      - run: |
              cd chatlyst-dev
              ls