name: Help Docs

on:
  push:
    branches: [develop]
    paths: ['chatlyst-dev/**','docs/**','README.md']
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  Docs:
    runs-on: windows-latest
    steps:
      - name: Checkout Self
        uses: actions/checkout@v3

      # Use the Readme.md as the first page
      - name: Set first page
        run: cp README.md docs/index.md
      
      - name: Setup Unity
        uses: kuler90/setup-unity@v1
        with:
          project-path: chatlyst-dev/
       
      - name: Activate Unity
        uses: Morsiusiurandum/activate-unity@v1.2.1
        with:
          unity-username: ${{ secrets.UNITY_EMAIL }}
          unity-password: ${{ secrets.UNITY_PASSWORD }}
          unity-serial: ${{ secrets.UNITY_SERIAL}}

      - name: Dotnet Setup
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x

      - name: Setup Docfx
        run: dotnet tool update -g docfx

      - name: Build Site
        run: docfx docs/docfx.json

      - name: Deploy site
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: docs/_site
