name: Help Docs

on:
  push:
   paths: ['chatlyst-dev/**','docs/**','README.md']
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  Docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Self
        uses: actions/checkout@v3

      # Use the Readme.md as the first page
      - name: Set first page
        run: cp README.md docs/index.md
      
      - name: Build site
        uses: nikeee/docfx-action@v1.0.0
        with:
          args: docs/docfx.json

      - name: Deploy site
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: docs/_site