name: Unit Test

on:
  pull_request_target:
    branches: [develop]
    types: [closed]
    paths: ['chatlyst-dev/**']
  workflow_dispatch: {}

jobs:
  Test:
    if: ${{ github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Self
        uses: actions/checkout@v3

      - name: Unit test
        id: Tests
        uses: game-ci/unity-test-runner@v3
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          projectPath: chatlyst-dev/
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          coverageOptions: 'generateAdditionalMetrics'

      - name: Upload XML report to Codecov
        uses: codecov/codecov-action@v2
        with:
          name: Results
          flags: automated
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ${{ steps.Tests.outputs.coveragePath }}/**/*.xml