name: Unit Test

on:
  pull_request_target:
    branches: [develop]
    types: [closed]
    paths: ['chatlyst-dev/**']
  workflow_dispatch: {}

jobs:
  test:
    if: ${{ github.event.pull_request.merged == true || github.event_name != 'workflow_dispatch'}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - uses: actions/cache@v2
        with:
          path: chatlyst-dev/Library
          key: Library-Chatlyst
          restore-keys: |
            Library-

      - name: Unit test
        id: Tests
        uses: game-ci/unity-test-runner@v3.1.0
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          projectPath: chatlyst-dev/
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          coverageOptions: 'generateAdditionalMetrics'
          
      - name: Upload XML report to Codecov
        uses: codecov/codecov-action@v2
        with:
          name: Results
          flags: automated
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ${{ steps.Tests.outputs.coveragePath }}/**/*.xml

  docs:
    name: Create docs
    
    runs-on: ubuntu-latest
    container: unityci/editor:ubuntu-2022.3.10f1-linux-il2cpp-2
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - uses: actions/cache@v2
        with:
          path: chatlyst-dev/Library
          key: Library-Chatlyst
          restore-keys: |
            Library-

      - name: Create ULF File
        uses: 1arp/create-a-file-action@0.3
        with:
          file: 'act.ulf'
          content: ${{ secrets.UNITY_LICENSE }}

      - name: Unity Activation    
        run : unity-editor -batchmode -nographics -quit -username ${{ secrets.UNITY_EMAIL }} - password ${{ secrets.UNITY_PASSWORD }} -manualLicenseFile act.ulf -projectPath chatlyst-dev

      - name: Generate .csproj
        run : unity-editor -batchmode -nographics -quit -projectPath chatlyst-dev -executeMethod Packages.Rider.Editor.RiderScriptEditor.SyncSolution

      - name: Dotnet Setup
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x

      - name: Setup Docfx
        run: dotnet tool update -g docfx

      - name: Build Site
        run: dotnet docfx docs/docfx.json

      - name: Deploy site
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: docs/_site
