name: Unit Test

on:
  pull_request:
    branches: [develop]
    paths: ['chatlyst-dev/**']
  push:
    branches: [develop]
    paths: ['chatlyst-dev/**']
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  Test:
    runs-on: windows-latest
    steps:
      - name: Checkout Self
        uses: actions/checkout@v3

      
      - name: Setup Unity
        id: setup
        uses: kuler90/setup-unity@v1
        with:
          project-path: chatlyst-dev/
       

  #    - name: Activate Unity
        #uses: Morsiusiurandum/activate-unity@v1.2.0
        #with:
          #unity-username: ${{ secrets.UNITY_EMAIL }}
          #unity-password: ${{ secrets.UNITY_PASSWORD }}
          #unity-serial: ${{ secrets.UNITY_SERIAL}}
          #unity-path: ${{steps.setup.output.unity-path}}

#      - # name: Unit test
        #id: Tests
        #uses: game-ci/unity-builder@v3
        #env:
          #UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          #UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          #UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        #with:
          #projectPath: chatlyst-dev/
          #targetPlatform: StandaloneWindows64
          
         # coverageOptions: 'generateAdditionalMetrics'
        #  buildMethod: SyncVS_Workaround.SyncSolution

      - run: |
              ls
              $evn:UNITY_PATH -batchmode -nographics -quit -projectPath chatlyst-dev -executeMethod SyncVS_Workaround.SyncSolution  -username ${{ secrets.UNITY_EMAIL }} -password ${{ secrets.UNITY_PASSWORD }} -serial ${{ secrets.UNITY_SERIAL }}
              
              cd chatlyst-dev
              ls







