name: Validate

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout self
        uses: actions/checkout@v3

      - uses: game-ci/unity-test-runner@v3
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          projectPath: chatlyst-dev/
          githubToken: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          ls